import locale
import datetime
import xml.etree.ElementTree as ET
import logging
import pyautogui as p
import datetime
def vba():
    try:
        tree = ET.parse("C:\\Users\\User\\Desktop\\206-BS-571\\diretório\\diretorio.xml")
        root2 = tree.getroot()
        for child2 in root2:
                for x2 in root2.findall(child2.tag):
                        vba1 = x2.find('vba1').text
                        vba = x2.find('vba').text
        data_atual = datetime.datetime.now()
        data = data_atual.date()
        locale.setlocale(locale.LC_ALL, '')
        ano = data.strftime("%Y")
        mes = data.strftime("%m")
        anoMes = data.strftime("%Y%m")
        diretorio = vba1 + 'Porcentagem moniopmeditoramento SIB X DW BS ' + mes + ano
        caminho = vba
        # RENOMEANDO COM MES E ANO ATUAL
        data_atual = datetime.datetime.now()
        data = data_atual.date()
        locale.setlocale(locale.LC_ALL, '')
        data_br = data.strftime("%b/%y")

        p.sleep(2)
        #importando vba
        p.hotkey('win','r')
        p.sleep(5)
        p.write(diretorio)
        p.sleep(1)
        p.press('enter')
        p.sleep(5)
        p.hotkey('alt','F11')#entra no vba
        p.sleep(3)
        p.hotkey('ctrl','m')#entra no local de importação
        p.sleep(1)
        p.press('tab')
        p.sleep(1)
        p.press('tab')
        p.sleep(1)
        p.press('tab')
        p.sleep(1)
        p.press('tab')
        p.sleep(1)
        p.press('tab')
        p.sleep(1)
        p.press('tab')
        p.sleep(1)
        p.write(caminho)
        p.sleep(2)
        p.press('tab')
        p.sleep(1)
        p.press('tab')
        p.sleep(1)
        p.press('tab')
        p.sleep(1)
        p.press('tab')
        p.sleep(1)
        p.write('M1')#escreve o arquivo que vai importar
        p.sleep(1)
        # p.press('tab')
        # p.sleep(1)
        # p.press('down')
        # p.sleep(1)
        # p.press('down')
        # p.sleep(1)
        # p.press('enter')
        # p.sleep(1)
        p.press('enter')
        p.sleep(3)
        p.hotkey('ctrl','m')
        p.sleep(1)
        p.write('M2')
        p.sleep(1)
        p.press('enter')
        p.sleep(3)
        p.hotkey('ctrl','m')
        p.sleep(1)
        p.write('M3')
        p.sleep(1)
        p.press('enter')
        p.sleep(3)
        p.hotkey('ctrl','m')
        p.sleep(1)
        p.write('M4')
        p.sleep(1)
        p.press('enter')
        p.sleep(3)
        p.hotkey('alt','F4')  
        p.sleep(1)
        #editando arquivo

        p.hotkey('alt','F8')
        p.sleep(3)
        p.press('tab')
        p.sleep(1)
        p.press('tab')
        p.sleep(1)
        p.press('tab')
        p.sleep(1)
        p.press('tab')
        p.sleep(1)
        p.press('tab')
        p.sleep(1)
        p.press('enter')
        p.sleep(5)
        p.press('down')
        p.sleep(1)
        p.press('down')
        p.sleep(1)
        p.press('down')
        p.sleep(1)
        p.press('down')
        p.sleep(1)
        p.press('down')
        p.sleep(1)
        p.press('down')
        p.sleep(1)
        p.press('down')
        p.sleep(1)
        p.press('down')
        p.sleep(1)
        p.press('down')
        p.sleep(1)
        p.press('down')
        p.sleep(1)
        p.press('right')
        p.sleep(1)
        p.press('right')
        p.sleep(1)
        p.press('right')
        p.sleep(1)
        p.press('right')
        p.sleep(1)
        p.press('right')
        p.sleep(1)
        p.press('right')
        p.sleep(1)
        p.press('right')
        p.sleep(1)
        p.press('right')
        p.sleep(1)
        p.press('right')
        p.sleep(1)
        p.press('right')
        p.sleep(1)
        p.press('right')
        p.sleep(1)
        p.press('right')
        p.sleep(1)
        p.press('right')
        p.sleep(1)
        p.press('right')
        p.sleep(1)
        p.press('right')
        p.sleep(1)
        p.press('right')
        p.sleep(1)
        p.press('right')
        p.sleep(1)
        p.press('right')
        p.sleep(1)
        p.press('right')
        p.sleep(1)
        p.press('right')
        p.sleep(1)
        p.press('right')
        p.sleep(1)
        p.press('right')
        p.sleep(1)
        p.press('right')
        p.sleep(1)
        p.press('right')
        p.sleep(1)
        p.press('right')
        p.sleep(1)
        p.press('right')
        p.sleep(1)
        p.press('right')
        p.sleep(1)
        p.press('right')
        p.sleep(1)
        p.press('right')
        p.sleep(1)
        p.press('right')
        p.sleep(1)
        p.press('right')
        p.sleep(1)
        p.press('right')
        p.sleep(1)
        p.press('right')
        p.sleep(1)
        p.press('right')
        p.sleep(1)
        p.press('right')
        p.sleep(1)
        p.press('right')
        p.sleep(1)
        p.press('right')
        p.sleep(1)
        p.press('right')
        p.sleep(1)
        p.press('right')
        p.sleep(1)
        p.press('right')
        p.sleep(1)
        p.press('right')
        p.sleep(1)
        p.press('right')
        p.sleep(1)
        p.press('right')
        p.sleep(1)
        p.press('right')
        p.sleep(1)
        p.press('right')
        p.sleep(1)
        p.press('delete')
        p.sleep(1)
        p.press('delete')
        p.sleep(1)
        p.press('delete')
        p.sleep(1)
        p.press('delete')
        p.sleep(1)
        p.press('delete')
        p.sleep(1)
        p.press('delete')
        p.sleep(1)
        p.write(data_br)
        # p.hotkey('ctrl','e')
        p.sleep(3)
        p.hotkey('alt','F4')   
        p.sleep(3)
        #EDITANDO 2° ARQUIVO

        p.hotkey('alt','F8')
        p.sleep(3)
        p.press('tab')
        p.sleep(1)
        p.press('down')
        p.sleep(1)
        p.press('down')
        p.sleep(1)
        p.press('tab')
        p.sleep(1)
        p.press('tab')
        p.sleep(1)
        p.press('tab')
        p.sleep(1)
        p.press('tab')
        p.sleep(1)
        p.press('enter')
        # p.sleep(2)
        # p.hotkey('ctrl','e')                    
        # p.sleep(2)
        # p.press('enter')
        p.sleep(5)
        p.press('down')
        p.sleep(1)
        p.press('down')
        p.sleep(1)
        p.press('down')
        p.sleep(1)
        p.press('down')
        p.sleep(1)
        p.press('down')
        p.sleep(1)
        p.press('down')
        p.sleep(1)
        p.press('down')
        p.sleep(1)
        p.press('down')
        p.sleep(1)
        p.press('down')
        p.sleep(1)
        p.press('down')
        p.sleep(1)
        p.press('right')
        p.sleep(1)
        p.press('right')
        p.sleep(1)
        p.press('right')
        p.sleep(1)
        p.press('right')
        p.sleep(1)
        p.press('right')
        p.sleep(1)
        p.press('right')
        p.sleep(1)
        p.press('right')
        p.sleep(1)
        p.press('right')
        p.sleep(1)
        p.press('right')
        p.sleep(1)
        p.press('right')
        p.sleep(1)
        p.press('right')
        p.sleep(1)
        p.press('right')
        p.sleep(1)
        p.press('right')
        p.sleep(1)
        p.press('right')
        p.sleep(1)
        p.press('right')
        p.sleep(1)
        p.press('right')
        p.sleep(1)
        p.press('right')
        p.sleep(1)
        p.press('right')
        p.sleep(1)
        p.press('right')
        p.sleep(1)
        p.press('right')
        p.sleep(1)
        p.press('right')
        p.sleep(1)
        p.press('right')
        p.sleep(1)
        p.press('right')
        p.sleep(1)
        p.press('right')
        p.sleep(1)
        p.press('right')
        p.sleep(1)
        p.press('right')
        p.sleep(1)
        p.press('right')
        p.sleep(1)
        p.press('right')
        p.sleep(1)
        p.press('right')
        p.sleep(1)
        p.press('right')
        p.sleep(1)
        p.press('right')
        p.sleep(1)
        p.press('right')
        p.sleep(1)
        p.press('right')
        p.sleep(1)
        p.press('right')
        p.sleep(1)
        p.press('right')
        p.sleep(1)
        p.press('right')
        p.sleep(1)
        p.press('right')
        p.sleep(1)
        p.press('right')
        p.sleep(1)
        p.press('right')
        p.sleep(1)
        p.press('right')
        p.sleep(1)
        p.press('right')
        p.sleep(1)
        p.press('right')
        p.sleep(1)
        p.press('right')
        p.sleep(1)
        p.press('right')
        p.sleep(1)
        p.press('right')
        p.sleep(1)
        p.press('delete')
        p.sleep(1)
        p.press('delete')
        p.sleep(1)
        p.press('delete')
        p.sleep(1)
        p.press('delete')
        p.sleep(1)
        p.press('delete')
        p.sleep(1)
        p.press('delete')
        p.sleep(1)
        p.write(data_br)
        p.sleep(3)
        p.hotkey('alt','F4')   
        p.sleep(3)
        #EDITANDO 3° ARQUIVO

        p.hotkey('alt','F8')
        p.sleep(3)
        p.press('tab')
        p.sleep(1)
        p.press('down')
        p.sleep(1)
        p.press('down')
        p.sleep(1)
        p.press('down')
        p.sleep(1)
        p.press('tab')
        p.sleep(1)
        p.press('tab')
        p.sleep(1)
        p.press('tab')
        p.sleep(1)
        p.press('tab')
        p.sleep(1)
        p.press('enter')
        # p.sleep(2)
        # p.hotkey('ctrl','e')                    
        # p.sleep(2)
        # p.press('enter')
        p.sleep(5)
        p.press('down')
        p.sleep(1)
        p.press('down')
        p.sleep(1)
        p.press('down')
        p.sleep(1)
        p.press('down')
        p.sleep(1)
        p.press('down')
        p.sleep(1)
        p.press('down')
        p.sleep(1)
        p.press('down')
        p.sleep(1)
        p.press('down')
        p.sleep(1)
        p.press('down')
        p.sleep(1)
        p.press('down')
        p.sleep(1)
        p.press('right')
        p.sleep(1)
        p.press('right')
        p.sleep(1)
        p.press('right')
        p.sleep(1)
        p.press('right')
        p.sleep(1)
        p.press('right')
        p.sleep(1)
        p.press('right')
        p.sleep(1)
        p.press('right')
        p.sleep(1)
        p.press('right')
        p.sleep(1)
        p.press('right')
        p.sleep(1)
        p.press('right')
        p.sleep(1)
        p.press('right')
        p.sleep(1)
        p.press('right')
        p.sleep(1)
        p.press('right')
        p.sleep(1)
        p.press('right')
        p.sleep(1)
        p.press('right')
        p.sleep(1)
        p.press('right')
        p.sleep(1)
        p.press('right')
        p.sleep(1)
        p.press('right')
        p.sleep(1)
        p.press('right')
        p.sleep(1)
        p.press('right')
        p.sleep(1)
        p.press('right')
        p.sleep(1)
        p.press('right')
        p.sleep(1)
        p.press('right')
        p.sleep(1)
        p.press('right')
        p.sleep(1)
        p.press('right')
        p.sleep(1)
        p.press('right')
        p.sleep(1)
        p.press('right')
        p.sleep(1)
        p.press('right')
        p.sleep(1)
        p.press('right')
        p.sleep(1)
        p.press('right')
        p.sleep(1)
        p.press('right')
        p.sleep(1)
        p.press('right')
        p.sleep(1)
        p.press('right')
        p.sleep(1)
        p.press('right')
        p.sleep(1)
        p.press('right')
        p.sleep(1)
        p.press('right')
        p.sleep(1)
        p.press('right')
        p.sleep(1)
        p.press('right')
        p.sleep(1)
        p.press('right')
        p.sleep(1)
        p.press('right')
        p.sleep(1)
        p.press('right')
        p.sleep(1)
        p.press('right')
        p.sleep(1)
        p.press('right')
        p.sleep(1)
        p.press('right')
        p.sleep(1)
        p.press('right')
        p.sleep(1)
        p.press('delete')
        p.sleep(1)
        p.press('delete')
        p.sleep(1)
        p.press('delete')
        p.sleep(1)
        p.press('delete')
        p.sleep(1)
        p.press('delete')
        p.sleep(1)
        p.press('delete')
        p.sleep(1)
        p.write(data_br)
        p.sleep(3)
        p.hotkey('alt','F4')   
        p.sleep(2)
        p.hotkey('alt','F4') 
        p.sleep(1)
        p.press('enter')
        p.sleep(1)
        p.press('right')
        p.sleep(1)
        p.press('enter')
        p.sleep(1)
        p.press('tab')
        p.sleep(1)
        p.press('down')
        p.sleep(1)
        p.press('down')
        p.sleep(1)
        p.press('enter')
        p.sleep(1)
        p.press('enter')
    except Exception as e: # work on python 3.x
        logging.exception('| Ocorreu um erro: | 3')
# p.sleep(3)
# p.hotkey('alt','F4')   
# p.sleep(3)
# p.hotkey('alt','F4')
# p.sleep(3)


#fazer a edição de cada modulo
